### ISSUE TITLE
System.AggregateException in CacheCow.Server.Core.Mvc v2.6.1 (v2.6.0 was fine)

### ISSUE THREAD

**Issue by jagbarcelo** [aliostad/CacheCow#243]
We have just upgraded CacheCow.Client and CacheCow.Server.Core.Mvc in our solution (currently at v2.5.8) to the most recent version (v2.6.1) and we receive this exception in the webserver side:

```
public static void Main(string[] args)
{
    CreateHostBuilder(args).Build().Run();   <--- Thrown here
}
```

```
System.AggregateException
  HResult=0x80131500
  Mensaje = Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: CacheCow.Server.ICachingPipeline Lifetime: Transient ImplementationType: CacheCow.Server.CachingPipeline': Unable to resolve service for type 'CacheCow.Server.HttpCachingOptions' while attempting to activate 'CacheCow.Server.CachingPipeline'.)
  Origen = Microsoft.Extensions.DependencyInjection
  Seguimiento de la pila:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at myWebsite.com.Program.Main(String[] args) in G:\Documents\GitLab\mySolution\myWebsite.com\Program.cs:line 11

  La excepción se generó originalmente en esta pila de llamadas:
	Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(System.Type, System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain, System.Reflection.ParameterInfo[], bool)
	Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.ResultCache, System.Type, System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain)
	Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Microsoft.Extensions.DependencyInjection.ServiceDescriptor, System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain, int)
	Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Microsoft.Extensions.DependencyInjection.ServiceDescriptor, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain)
	Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(Microsoft.Extensions.DependencyInjection.ServiceDescriptor)

Excepción interna 1:
InvalidOperationException: Error while validating the service descriptor 'ServiceType: CacheCow.Server.ICachingPipeline Lifetime: Transient ImplementationType: CacheCow.Server.CachingPipeline': Unable to resolve service for type 'CacheCow.Server.HttpCachingOptions' while attempting to activate 'CacheCow.Server.CachingPipeline'.

Excepción interna 2:
InvalidOperationException: Unable to resolve service for type 'CacheCow.Server.HttpCachingOptions' while attempting to activate 'CacheCow.Server.CachingPipeline'.

```

Just by downgrading to v2.6.0 the exception goes away, so there must be something done within those 2 versions.

In our Startup class we have:

```
public void ConfigureServices(IServiceCollection services)
{
   …
   
   services.AddHttpCachingMvc(); // add HTTP Caching for Core MVC

   // https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.0
   // Register our CacheCow Inversion of Control (IoC) handlers
   services.AddTransient<CacheCow.Server.ISerialiser, myWebsite.com.App_Code.MyJsonSerialiser>();
   services.AddTransient<CacheCow.Server.ICacheabilityValidator, myWebsite.com.App_Code.MyCacheabilityValidator>();

   …

}
```

Commenting out our custom dependency injections (serialiser and cache validator) does not affect at all. The same exception is thrown anyway.

**Comment by aliostad** [comment]
Sorry for your issue. I will investigate and fix hopefully tonight. Thanks for creating the issue.

**Comment by aliostad** [comment]
Please try 2.6.2. It should have been fixed. It was missing one registration.

**Comment by jagbarcelo** [comment]
Yes, version 2.6.2 works fine. Thanks a lot for such a quick fix and release.

**Comment by aliostad** [comment]
Well, thank *you* for raising this. Cheers!
