### ISSUE TITLE
How to register ITimedETagExtractor when ViewModelType is used

### ISSUE THREAD

**Issue by jagbarcelo** [aliostad/CacheCow#249]
I have created a class:
```
public class Response_TimedETagExtractor : ITimedETagExtractor<Response>
{
...
```

... decorated the method in the controller with:
```
[HttpCacheFactory(600, ViewModelType = typeof(Response))] 
public IActionResult Get([FromRoute] Guid userId, [FromRoute] Guid id)
{
...
```

… and registered it in `ConfigureServices(IServiceCollection services)` via:
```
services.AddHttpCachingMvc(); // add HTTP Caching for Core MVC
services.AddTransient<CacheCow.Server.ISerialiser, App_Code.MyJsonSerialiser>();
services.AddTransient<CacheCow.Server.ICacheabilityValidator, App_Code.MyCacheabilityValidator>();
services.AddSingleton<ITimedETagExtractor<Response>, Response_TimedETagExtractor>();
```

However, it seems that this registration is wrong. Because I am receiving the following exception:

```
Exception Type: System.InvalidOperationException
HResult:        -2146233079
Message:        Could not resolve the filter or its dependencies. If you have defined ViewModelType, make sure that at least one generic registration is done using ConfigurationExtensions.
Source:         CacheCow.Server.Core.Mvc
Stack Trace:
   at CacheCow.Server.Core.Mvc.HttpCacheFactoryAttribute.CreateInstance(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Mvc.Filters.DefaultFilterProvider.ProvideFilter(FilterProviderContext context, FilterItem filterItem)
   at Microsoft.AspNetCore.Mvc.Filters.DefaultFilterProvider.OnProvidersExecuting(FilterProviderContext context)
   at Microsoft.AspNetCore.Mvc.Filters.FilterFactory.CreateUncachedFiltersCore(IFilterProvider[] filterProviders, ActionContext actionContext, List1 filterItems)
   at Microsoft.AspNetCore.Mvc.Filters.FilterFactory.GetAllFilters(IFilterProvider[] filterProviders, ActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerCache.GetCachedResult(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.<>c__DisplayClass7_0.<CreateRequestDelegate>b__0(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
```

Any other way to do it? Or might it be that it needs to be done before (or after) any other thing?

We are running CacheCow.Server.Core.Mvc 2.7.0. Thanks

**Comment by aliostad** [comment]
Sorry for late reply. I am going to provide a fluent syntax for configuration in the next minor release.

But in the meantime, there are extensions already in the library that you need to use. Have a look [here](https://github.com/aliostad/CacheCow/blob/master/src/CacheCow.Server.Core.Mvc/ConfigurationExtensions.cs#L71) and the [samples](https://github.com/aliostad/CacheCow/blob/master/samples/CacheCow.Samples.MvcCore/Startup.cs#L29) please.

I believe you need `AddExtractorForViewModelMvc` extension based on your scenario. There are other extensions depending on which ones you have implemented. This will be simplified by adding fluent syntax which I will do soon.
